name: 'Ytmusic_analytics_V2'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# ================================
# GLOBAL SETTINGS
# ================================
models:
  Ytmusic_analytics_V2:

    # -----------------------------
    # 1. STAGING LAYER
    # -----------------------------
    staging:
      +schema: ytmusic_staging
      +materialized: view
      +tags: ['staging']

    # -----------------------------
    # 2. INTERMEDIATE LAYER
    # -----------------------------
    intermediate:
      +schema: ytmusic_intermediate
      +materialized: view
      +tags: ['intermediate']

    # -----------------------------
    # 3. MARTS LAYER
    # -----------------------------
    mart:
      +schema: ytmusic_mart
      +materialized: table
      +persist_docs:
          relation: true
          columns: true
      +tags: ['mart']
